version: "3.7"

networks:
  my-network:

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - 9000
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - web_vol:/var/www/html/wordpress
    networks:
      - my-network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - 3306
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - my-network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - web_vol:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - my-network
    restart: always
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    image: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - my-network
    restart: always
  adminer:
    build: ./requirements/bonus/adminer/.
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - my-network
    restart: always
  static-website:
    container_name: static-website
    build: ./requirements/bonus/website/.
    image: static-website
    ports:
      - 8000:1337
    networks:
      - my-network
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    image: redis
    ports: 
      - 6379:6379
    volumes:
      - web_vol:/var/www/html/wordpress
    networks:
      - my-network
    restart: always

volumes:
  mariadb_vol:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/sgmira/Desktop/Data/mariadb_vol
  web_vol:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/sgmira/Desktop/Data/web_vol
